version: '3.8'

services:
  dashboard:
    ports:
      - '3001:3000'
      - '4317:4317'
      - '4318:4318'
    image: 'grafana/otel-lgtm:latest'

  mongo:
    image: mongo:7
    container_name: mongo-db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
